<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Medicine;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $today = Carbon::today();
        $categories = Category::pluck('id', 'name');

        $images = [
            'paracetamol' => 'https://sspark.genspark.ai/cfimages?u1=0%2FBHQ2pSFP0vQ3XB3xIPX13ElEEdne7CH7GzcNkAMlVS0fQ7ZoBy8rUqa0dmBIY9RuR8P2ias2sOIaRRppVN6ShwSbpHzERzQNabQwuljWsfVk4%2FHbvqOh%2Bs279CO9FWwXuASPU%3D&u2=5K04CLlxvU2sfEDz&width=2560',
            'ibuprofen' => 'https://sspark.genspark.ai/cfimages?u1=hp12Zf6vENAZhM2Yy7aTmbkoULFXVUTqyqu1HL4%2BXSf8hq3p%2FQVZIDIPzsg%2B%2FHiF6qZDy9vyDg%2BuWyqYluR8kAb09erHSX99kM6lBkXiz4M15EODTrKB7ZobyfRJ8FfsERFoSg%3D%3D&u2=0%2BTeZxU20KE%2FixjB&width=2560',
            'amoxicillin_capsules' => 'https://sspark.genspark.ai/cfimages?u1=259podtZ%2FD72AgXdrAsn8amyn6ejC2Nc%2FmEEc0QTcxLZum60N3FHnHtZ%2BhKjPkPm%2B%2FP4zBJT3m8oBvgw7M40plOfDSOG4vtHHaLY3pV%2Fs2gKCQZ%2FaETDYkt91rgphdwr9U5rnhxcIgCcT9Hx9YJYb%2BAOSDQ1BTLaBoc%3D&u2=SYgG5vOZfOEK2nGg&width=2560',
            'amoxicillin_box' => 'https://sspark.genspark.ai/cfimages?u1=zcZ1yHKrfJqPfC5frEQkcglFsxwJnet8FtZVUVGkq%2BUVIZpQJlK9TxlMS0ZnGYs3AZB3BIHaB5s3PQOp8%2B52VK0dwgrA7TlmZbV87s9w5t7msVbGk%2FI8kqGHbVNi3v6qSTznfwNsR4Dd8jd234cLj0p5eg%3D%3D&u2=%2FOV0HC%2FptzGjI%2Bfg&width=2560',
            'amoxicillin_drops' => 'https://sspark.genspark.ai/cfimages?u1=WGkl3jJhK6Si1P1BYWJ0T219iGsezEpjYawtknt08FSAZuYXy%2BOLqNdv4ktuaESxQPs27XJTsnU5a0xi2FDjrFSBnh0AT4mCbny7Wl3nFoX855VxahcIsVmpRjj7V87%2F3cg%3D&u2=93TH4am9TdjIhBUd&width=2560',
            'azithromycin' => 'https://sspark.genspark.ai/cfimages?u1=ClrjUUcpfDRgy8lfBggB534p9B776qMBFyEo%2FPd%2Fx9x6x8qo5pXjAspFdaxM6kdSuog7sfqacPEVVK39qWXs%2Fz69pwpTwpkQGb11LymJtClB%2FtjHQd7JVbFlf%2BZ1WL6agEmiyqFwcmrg2sVUPjYw&u2=2y4SEhBJtMsQ4rUG&width=2560',
            'prescription_bottles' => 'https://sspark.genspark.ai/cfimages?u1=LrlZF82%2BK%2FYSua9Jkd8G4SnxJAYrzJVLSoSwoF85PnXFADkYxHDIE7eFxVcklG4MyfZJBCrTbiaRlAdAVNYvj9jO3oDa3E6AlZPsd1CiuWXNwA4Wfbkv7Bd1BqFDFwJSRkRdzZXeAHtNZ%2BWpv%2BD3f%2F0cH5AIrA%3D%3D&u2=1%2Bu7zpIpCQvtvkNz&width=2560',
            'vitamin_pills' => 'https://sspark.genspark.ai/cfimages?u1=Z7aYxs0fiIPOQBeGr8wZpbvFHzk90PV%2FIZ%2Bk70peCCDXTfiGHmRiXex6bhuPByXN4TnwQtX%2FRdiJdeuYv0XcltCmoyh9%2BF248Kd8jjd6FGbtDb8%2FPs9SxdVEGhl0oao%3D&u2=pWXkndYWlJk8veJU&width=2560',
            'prenatal_vitamins' => 'https://sspark.genspark.ai/cfimages?u1=auKqcWisRVpDrEvbrNurv0U%2B1CLH0Dho4m9vqA9sT6I5bIAHJRd79vQxT7hpBzfIsTo4B6DqqxwABZ1VUAbx0Q10lnkIU8ocSDPuWujkE2FMMRn73zi8jfziT8L%2Bm5n5&u2=lkDWqDCj5qqDcSBb&width=2560',
            'centrum' => 'https://sspark.genspark.ai/cfimages?u1=FnQwPOPP%2FSD8T7VCkMNNixfi7cWsWzyihHxh8JbdC6KJT5CkLWCTBXSm%2BCGmCmRPwYdVgsbgBqYvFZPpNSHRx55Ad7u8IO0G5NF7t0pvJ49Wai%2Fmgg%3D%3D&u2=373%2FqGc%2BErkece%2FY&width=2560',
            'b12' => 'https://sspark.genspark.ai/cfimages?u1=aRErfsFWZdm4JW8FVDcJ%2BG5r0wEOLBrRG%2FuuWDEmaZULYtl70E5Pm1JX8Da29XtW%2FoE9bimhj%2FZFe%2ByzMeGHbsuyCk9%2FmqOIZFqIjcNRrF3WOhRQrdH9aMHFKig61Us%3D&u2=8hWGDaQxybgRFFcu&width=2560',
            'azelaic_cream' => 'https://sspark.genspark.ai/cfimages?u1=%2B9w4iIMWsztQz5uLETVYBOv34VlnLhOJz3CLdSEwGKKk%2B%2BnBdHn%2Bt9zw0nxa7%2F%2BnHo1CxMkg8zk%2Fpa9o9DTN6g0i4cIzfZULHZMuHHtx7lN%2Flo0Pxd994NoR0jYFSge0tsz3&u2=Y9ozuwKRICxk40Sr&width=2560',
            'boroline' => 'https://sspark.genspark.ai/cfimages?u1=VJxnluVmS5NWMimTD%2FzmtMxDw%2FQbSdWBJtiXdPL8NepFywT%2BP2Ux0eXghnc6GSv7EkYzwEjaDSSsBO3pUwqZmVIiCy9tpnyCYTm79JLwBv94eD8CKe8A59T7P6emUXQCww%3D%3D&u2=ll6KFGQ7%2Fe2U7uYF&width=2560',
            'e45' => 'https://sspark.genspark.ai/cfimages?u1=5v7en%2Bh90bizvb5wo2wkvsGMBcZjv1KVFvTWvsNUU0lSVfRJBjIzgMJT8Vdl57RKzgUDFsHVAjNMwkqPC7oAYldXnI0BboYqIf2AnTjlCuCZMD4iuQhEcA%3D%3D&u2=7jxflId%2BCVKBDr3o&width=2560',
            'assorted_pills' => 'https://sspark.genspark.ai/cfimages?u1=0%2FBHQ2pSFP0vQ3XB3xIPX13ElEEdne7CH7GzcNkAMlVS0fQ7ZoBy8rUqa0dmBIY9RuR8P2ias2sOIaRRppVN6ShwSbpHzERzQNabQwuljWsfVk4%2FHbvqOh%2Bs279CO9FWwXuASPU%3D&u2=5K04CLlxvU2sfEDz&width=2560',
            'duodart' => 'https://sspark.genspark.ai/cfimages?u1=6YkuUFxOObTooWPPdNqOIx9E%2FZl%2FqCyH9pzk9xzzwfKRQIRKKD5TGtnIi9gkX9XRiHg%2B%2FSiKuLISFlRaT3g9PBOBjZ1qtVZAkjbmWaRTKJ5PouWVOKXfidFJ1eSbvH4iBBM%3D&u2=l7TeQIEzX0h0Mo4b&width=2560',
            'medicine_bottle' => 'https://sspark.genspark.ai/cfimages?u1=kURZZEJCT%2BpsAB2%2FI8RRXXqWcFpljYNyHxOb76tcIBiED%2B3dAw%2BW36GhbkngiDBBbnMQh8MvB5RSWazxLN43i09Ay46Tl9Zs8FWVHgJCkw6fBqrKJCX6%2B0YVkTNQAqJVQrnTn8tJOYZ8M6htsJHl86vVjFM%3D&u2=jkRMucnnemn5L8vO&width=2560',
        ];

        $medicines = [
            [
                'nom' => 'Doliprane',
                'dci' => 'Paracétamol',
                'molecule' => 'Paracétamol',
                'code' => 'MED-0001',
                'category' => 'Antalgiques',
                'dose' => '1000 mg comprimé',
                'stock' => 180,
                'prix' => 15.50,
                'exp' => $today->copy()->addMonths(18)->format('Y-m-d'),
                'description' => 'Traitement symptomatique de la douleur et de la fièvre chez l’adulte.',
                'image_url' => $images['paracetamol'],
                'ordonnance' => false,
                'seuil_alerte' => 20,
                'translations' => [
                    'fr' => [
                        'nom' => 'Doliprane',
                        'dci' => 'Paracétamol',
                        'dose' => '1000 mg comprimé',
                        'description' => 'Traitement symptomatique de la douleur et de la fièvre chez l’adulte.',
                    ],
                    'en' => [
                        'nom' => 'Doliprane',
                        'dci' => 'Paracetamol',
                        'dose' => '1000 mg tablet',
                        'description' => 'Symptomatic treatment for pain and fever in adults.',
                    ],
                    'ar' => [
                        'nom' => 'دوليبران',
                        'dci' => 'باراسيتامول',
                        'dose' => '1000 ملغ أقراص',
                        'description' => 'علاج عرضي للألم والحمى لدى البالغين.',
                    ],
                ],
            ],
            [
                'nom' => 'Advil',
                'dci' => 'Ibuprofène',
                'molecule' => 'Ibuprofène',
                'code' => 'MED-0002',
                'category' => 'Antalgiques',
                'dose' => '400 mg capsule',
                'stock' => 48,
                'prix' => 28.00,
                'exp' => $today->copy()->addMonths(12)->format('Y-m-d'),
                'description' => 'Anti-inflammatoire non stéroïdien indiqué contre les douleurs et migraines.',
                'image_url' => $images['ibuprofen'],
                'ordonnance' => false,
                'seuil_alerte' => 12,
                'translations' => [
                    'fr' => [
                        'nom' => 'Advil',
                        'dci' => 'Ibuprofène',
                        'dose' => '400 mg capsule',
                        'description' => 'Anti-inflammatoire non stéroïdien indiqué contre les douleurs et migraines.',
                    ],
                    'en' => [
                        'nom' => 'Advil',
                        'dci' => 'Ibuprofen',
                        'dose' => '400 mg capsule',
                        'description' => 'NSAID used for pain and migraine relief.',
                    ],
                    'ar' => [
                        'nom' => 'أدفيل',
                        'dci' => 'إيبوبروفين',
                        'dose' => '400 ملغ كبسولة',
                        'description' => 'مضاد التهاب غير ستيرويدي لتخفيف الألم والصداع النصفي.',
                    ],
                ],
            ],
            [
                'nom' => 'Efferalgan Vitamine C',
                'dci' => 'Paracétamol + Acide ascorbique',
                'molecule' => 'Paracétamol + vitamine C',
                'code' => 'MED-0003',
                'category' => 'Antalgiques',
                'dose' => '330 mg / 200 mg comprimé effervescent',
                'stock' => 60,
                'prix' => 24.90,
                'exp' => $today->copy()->addMonths(14)->format('Y-m-d'),
                'description' => 'Antalgique et antipyrétique effervescent utilisé lors des états grippaux.',
                'image_url' => $images['vitamin_pills'],
                'ordonnance' => false,
                'seuil_alerte' => 10,
                'translations' => [
                    'fr' => [
                        'nom' => 'Efferalgan Vitamine C',
                        'dci' => 'Paracétamol + Acide ascorbique',
                        'dose' => '330 mg / 200 mg comprimé effervescent',
                        'description' => 'Antalgique et antipyrétique effervescent utilisé lors des états grippaux.',
                    ],
                    'en' => [
                        'nom' => 'Efferalgan Vitamin C',
                        'dci' => 'Paracetamol + Ascorbic acid',
                        'dose' => '330 mg / 200 mg effervescent tablet',
                        'description' => 'Effervescent pain reliever and antipyretic commonly used with flu-like symptoms.',
                    ],
                    'ar' => [
                        'nom' => 'إيفيرالغان فيتامين سي',
                        'dci' => 'باراسيتامول + حمض الأسكوربيك',
                        'dose' => '330 ملغ / 200 ملغ أقراص فوارة',
                        'description' => 'مسكن وخافض للحرارة فوار يُستعمل في حالات الزكام والإنفلونزا.',
                    ],
                ],
            ],
            [
                'nom' => 'Amoxicilline Biogaran',
                'dci' => 'Amoxicilline',
                'molecule' => 'Amoxicilline trihydrate',
                'code' => 'MED-0004',
                'category' => 'Antibiotiques',
                'dose' => '1 g comprimé dispersible',
                'stock' => 42,
                'prix' => 52.90,
                'exp' => $today->copy()->addMonths(10)->format('Y-m-d'),
                'description' => 'Antibiotique à large spectre pour infections bactériennes sensibles.',
                'image_url' => $images['amoxicillin_capsules'],
                'ordonnance' => true,
                'seuil_alerte' => 10,
                'translations' => [
                    'fr' => [
                        'nom' => 'Amoxicilline Biogaran',
                        'dci' => 'Amoxicilline',
                        'dose' => '1 g comprimé dispersible',
                        'description' => 'Antibiotique à large spectre pour infections bactériennes sensibles.',
                    ],
                    'en' => [
                        'nom' => 'Amoxicillin Biogaran',
                        'dci' => 'Amoxicillin',
                        'dose' => '1 g dispersible tablet',
                        'description' => 'Broad-spectrum antibiotic for susceptible bacterial infections.',
                    ],
                    'ar' => [
                        'nom' => 'أموكسيسيلين بيوغاران',
                        'dci' => 'أموكسيسيلين',
                        'dose' => '1 غ قرص قابل للذوبان',
                        'description' => 'مضاد حيوي واسع الطيف للعدوى البكتيرية الحساسة.',
                    ],
                ],
            ],
            [
                'nom' => 'Azithromycine',
                'dci' => 'Azithromycine',
                'molecule' => 'Azithromycine dihydrate',
                'code' => 'MED-0005',
                'category' => 'Antibiotiques',
                'dose' => '500 mg comprimé',
                'stock' => 18,
                'prix' => 89.00,
                'exp' => $today->copy()->addMonths(8)->format('Y-m-d'),
                'description' => 'Antibiotique macrolide prescrit dans certaines infections ORL et respiratoires.',
                'image_url' => $images['azithromycin'],
                'ordonnance' => true,
                'seuil_alerte' => 8,
                'translations' => [
                    'fr' => [
                        'nom' => 'Azithromycine',
                        'dci' => 'Azithromycine',
                        'dose' => '500 mg comprimé',
                        'description' => 'Antibiotique macrolide prescrit dans certaines infections ORL et respiratoires.',
                    ],
                    'en' => [
                        'nom' => 'Azithromycin',
                        'dci' => 'Azithromycin',
                        'dose' => '500 mg tablet',
                        'description' => 'Macrolide antibiotic prescribed for selected ENT and respiratory infections.',
                    ],
                    'ar' => [
                        'nom' => 'أزيثروميسين',
                        'dci' => 'أزيثروميسين',
                        'dose' => '500 ملغ أقراص',
                        'description' => 'مضاد حيوي من عائلة الماكروليد لبعض التهابات الأنف والأذن والحنجرة والجهاز التنفسي.',
                    ],
                ],
            ],
            [
                'nom' => 'Augmentin',
                'dci' => 'Amoxicilline + Acide clavulanique',
                'molecule' => 'Amoxicilline trihydrate + clavulanate de potassium',
                'code' => 'MED-0006',
                'category' => 'Antibiotiques',
                'dose' => '1 g / 125 mg comprimé',
                'stock' => 21,
                'prix' => 78.50,
                'exp' => $today->copy()->addMonths(11)->format('Y-m-d'),
                'description' => 'Association antibiotique utilisée dans de nombreuses infections bactériennes documentées.',
                'image_url' => $images['amoxicillin_box'],
                'ordonnance' => true,
                'seuil_alerte' => 10,
                'translations' => [
                    'fr' => [
                        'nom' => 'Augmentin',
                        'dci' => 'Amoxicilline + Acide clavulanique',
                        'dose' => '1 g / 125 mg comprimé',
                        'description' => 'Association antibiotique utilisée dans de nombreuses infections bactériennes documentées.',
                    ],
                    'en' => [
                        'nom' => 'Augmentin',
                        'dci' => 'Amoxicillin + Clavulanic acid',
                        'dose' => '1 g / 125 mg tablet',
                        'description' => 'Antibiotic combination used for a wide range of documented bacterial infections.',
                    ],
                    'ar' => [
                        'nom' => 'أوغمنتين',
                        'dci' => 'أموكسيسيلين + حمض كلافولانيك',
                        'dose' => '1 غ / 125 ملغ أقراص',
                        'description' => 'تركيبة مضاد حيوي تُستعمل في عدد كبير من الالتهابات البكتيرية المؤكدة.',
                    ],
                ],
            ],
            [
                'nom' => 'Vitamine C UPSA',
                'dci' => 'Acide ascorbique',
                'molecule' => 'Acide ascorbique',
                'code' => 'MED-0007',
                'category' => 'Vitamines & Compléments',
                'dose' => '1000 mg effervescent',
                'stock' => 95,
                'prix' => 36.00,
                'exp' => $today->copy()->addMonths(16)->format('Y-m-d'),
                'description' => 'Complément utilisé en cas de fatigue passagère et de besoins accrus en vitamine C.',
                'image_url' => $images['vitamin_pills'],
                'ordonnance' => false,
                'seuil_alerte' => 15,
                'translations' => [
                    'fr' => [
                        'nom' => 'Vitamine C UPSA',
                        'dci' => 'Acide ascorbique',
                        'dose' => '1000 mg effervescent',
                        'description' => 'Complément utilisé en cas de fatigue passagère et de besoins accrus en vitamine C.',
                    ],
                    'en' => [
                        'nom' => 'Vitamin C UPSA',
                        'dci' => 'Ascorbic acid',
                        'dose' => '1000 mg effervescent',
                        'description' => 'Supplement used for temporary fatigue and increased vitamin C requirements.',
                    ],
                    'ar' => [
                        'nom' => 'فيتامين سي أوبسا',
                        'dci' => 'حمض الأسكوربيك',
                        'dose' => '1000 ملغ فوار',
                        'description' => 'مكمل يُستعمل في حالات التعب المؤقت وزيادة الحاجة إلى فيتامين سي.',
                    ],
                ],
            ],
            [
                'nom' => 'Magnésium B6',
                'dci' => 'Magnésium + Vitamine B6',
                'molecule' => 'Lactate de magnésium + pyridoxine',
                'code' => 'MED-0008',
                'category' => 'Vitamines & Compléments',
                'dose' => '470 mg / 5 mg comprimé',
                'stock' => 32,
                'prix' => 44.50,
                'exp' => $today->copy()->addMonths(12)->format('Y-m-d'),
                'description' => 'Association conseillée lors de fatigue nerveuse ou musculaire.',
                'image_url' => $images['prenatal_vitamins'],
                'ordonnance' => false,
                'seuil_alerte' => 10,
                'translations' => [
                    'fr' => [
                        'nom' => 'Magnésium B6',
                        'dci' => 'Magnésium + Vitamine B6',
                        'dose' => '470 mg / 5 mg comprimé',
                        'description' => 'Association conseillée lors de fatigue nerveuse ou musculaire.',
                    ],
                    'en' => [
                        'nom' => 'Magnesium B6',
                        'dci' => 'Magnesium + Vitamin B6',
                        'dose' => '470 mg / 5 mg tablet',
                        'description' => 'Combination recommended for nervous or muscular fatigue.',
                    ],
                    'ar' => [
                        'nom' => 'مغنيسيوم B6',
                        'dci' => 'مغنيسيوم + فيتامين B6',
                        'dose' => '470 ملغ / 5 ملغ أقراص',
                        'description' => 'تركيبة موصى بها في حالات التعب العصبي أو العضلي.',
                    ],
                ],
            ],
            [
                'nom' => 'Centrum',
                'dci' => 'Multivitamines et minéraux',
                'molecule' => 'Complexe multivitaminé',
                'code' => 'MED-0009',
                'category' => 'Vitamines & Compléments',
                'dose' => '1 comprimé par jour',
                'stock' => 26,
                'prix' => 79.00,
                'exp' => $today->copy()->addMonths(15)->format('Y-m-d'),
                'description' => 'Complément multivitaminé pour couvrir les besoins nutritionnels quotidiens.',
                'image_url' => $images['centrum'],
                'ordonnance' => false,
                'seuil_alerte' => 8,
                'translations' => [
                    'fr' => [
                        'nom' => 'Centrum',
                        'dci' => 'Multivitamines et minéraux',
                        'dose' => '1 comprimé par jour',
                        'description' => 'Complément multivitaminé pour couvrir les besoins nutritionnels quotidiens.',
                    ],
                    'en' => [
                        'nom' => 'Centrum',
                        'dci' => 'Multivitamins and minerals',
                        'dose' => '1 tablet daily',
                        'description' => 'Multivitamin supplement designed to cover daily nutritional needs.',
                    ],
                    'ar' => [
                        'nom' => 'سنتروم',
                        'dci' => 'متعدد الفيتامينات والمعادن',
                        'dose' => 'قرص واحد يومياً',
                        'description' => 'مكمل متعدد الفيتامينات لتغطية الاحتياجات الغذائية اليومية.',
                    ],
                ],
            ],
            [
                'nom' => 'Biafine',
                'dci' => 'Trolamine',
                'molecule' => 'Trolamine',
                'code' => 'MED-0010',
                'category' => 'Dermatologie',
                'dose' => 'Émulsion cutanée 93 g',
                'stock' => 27,
                'prix' => 48.00,
                'exp' => $today->copy()->addMonths(9)->format('Y-m-d'),
                'description' => 'Crème apaisante pour les brûlures superficielles et irritations cutanées.',
                'image_url' => $images['e45'],
                'ordonnance' => false,
                'seuil_alerte' => 8,
                'translations' => [
                    'fr' => [
                        'nom' => 'Biafine',
                        'dci' => 'Trolamine',
                        'dose' => 'Émulsion cutanée 93 g',
                        'description' => 'Crème apaisante pour les brûlures superficielles et irritations cutanées.',
                    ],
                    'en' => [
                        'nom' => 'Biafine',
                        'dci' => 'Trolamine',
                        'dose' => 'Skin emulsion 93 g',
                        'description' => 'Soothing cream for minor burns and skin irritation.',
                    ],
                    'ar' => [
                        'nom' => 'بيافين',
                        'dci' => 'ترولامين',
                        'dose' => 'مستحلب جلدي 93 غ',
                        'description' => 'كريم مهدئ للحروق السطحية وتهيجات الجلد.',
                    ],
                ],
            ],
            [
                'nom' => 'Cicalfate',
                'dci' => 'Sucralfate + cuivre/zinc',
                'molecule' => 'Sucralfate + sulfate de cuivre + sulfate de zinc',
                'code' => 'MED-0011',
                'category' => 'Dermatologie',
                'dose' => 'Crème réparatrice 40 ml',
                'stock' => 24,
                'prix' => 96.00,
                'exp' => $today->copy()->addMonths(14)->format('Y-m-d'),
                'description' => 'Crème réparatrice pour peaux irritées ou fragilisées.',
                'image_url' => $images['azelaic_cream'],
                'ordonnance' => false,
                'seuil_alerte' => 6,
                'translations' => [
                    'fr' => [
                        'nom' => 'Cicalfate',
                        'dci' => 'Sucralfate + cuivre/zinc',
                        'dose' => 'Crème réparatrice 40 ml',
                        'description' => 'Crème réparatrice pour peaux irritées ou fragilisées.',
                    ],
                    'en' => [
                        'nom' => 'Cicalfate',
                        'dci' => 'Sucralfate + copper/zinc',
                        'dose' => 'Repair cream 40 ml',
                        'description' => 'Repair cream for irritated or fragile skin.',
                    ],
                    'ar' => [
                        'nom' => 'سيكالفات',
                        'dci' => 'سكرالفات + نحاس/زنك',
                        'dose' => 'كريم مرمم 40 مل',
                        'description' => 'كريم مرمم للبشرة المتهيجة أو الحساسة.',
                    ],
                ],
            ],
            [
                'nom' => 'Boroline',
                'dci' => 'Antiseptique local',
                'molecule' => 'Acide borique + oxyde de zinc + lanoline',
                'code' => 'MED-0012',
                'category' => 'Dermatologie',
                'dose' => 'Crème antiseptique 20 g',
                'stock' => 14,
                'prix' => 34.00,
                'exp' => $today->copy()->addMonths(13)->format('Y-m-d'),
                'description' => 'Crème antiseptique et protectrice pour petites irritations cutanées.',
                'image_url' => $images['boroline'],
                'ordonnance' => false,
                'seuil_alerte' => 5,
                'translations' => [
                    'fr' => [
                        'nom' => 'Boroline',
                        'dci' => 'Antiseptique local',
                        'dose' => 'Crème antiseptique 20 g',
                        'description' => 'Crème antiseptique et protectrice pour petites irritations cutanées.',
                    ],
                    'en' => [
                        'nom' => 'Boroline',
                        'dci' => 'Topical antiseptic',
                        'dose' => 'Antiseptic cream 20 g',
                        'description' => 'Protective antiseptic cream for minor skin irritation.',
                    ],
                    'ar' => [
                        'nom' => 'بورولين',
                        'dci' => 'مطهر موضعي',
                        'dose' => 'كريم مطهر 20 غ',
                        'description' => 'كريم مطهر وواقٍ للتهيجات الجلدية البسيطة.',
                    ],
                ],
            ],
            [
                'nom' => 'Humex Rhume',
                'dci' => 'Paracétamol + pseudoéphédrine + doxylamine',
                'molecule' => 'Paracétamol + pseudoéphédrine + doxylamine',
                'code' => 'MED-0013',
                'category' => 'ORL & Rhume',
                'dose' => 'Comprimé jour / nuit',
                'stock' => 38,
                'prix' => 42.00,
                'exp' => $today->copy()->addMonths(12)->format('Y-m-d'),
                'description' => 'Traitement symptomatique du rhume avec nez bouché, céphalées et écoulement nasal.',
                'image_url' => $images['prescription_bottles'],
                'ordonnance' => false,
                'seuil_alerte' => 10,
                'translations' => [
                    'fr' => [
                        'nom' => 'Humex Rhume',
                        'dci' => 'Paracétamol + pseudoéphédrine + doxylamine',
                        'dose' => 'Comprimé jour / nuit',
                        'description' => 'Traitement symptomatique du rhume avec nez bouché, céphalées et écoulement nasal.',
                    ],
                    'en' => [
                        'nom' => 'Humex Cold',
                        'dci' => 'Paracetamol + pseudoephedrine + doxylamine',
                        'dose' => 'Day / night tablet',
                        'description' => 'Symptomatic treatment for colds with nasal congestion, headache and runny nose.',
                    ],
                    'ar' => [
                        'nom' => 'هيوميكس للزكام',
                        'dci' => 'باراسيتامول + سودوإيفيدرين + دوكسيلامين',
                        'dose' => 'أقراص نهارية / ليلية',
                        'description' => 'علاج عرضي للزكام المصحوب بانسداد الأنف والصداع وسيلان الأنف.',
                    ],
                ],
            ],
            [
                'nom' => 'Maxilase',
                'dci' => 'Alpha-amylase',
                'molecule' => 'Alpha-amylase',
                'code' => 'MED-0014',
                'category' => 'ORL & Rhume',
                'dose' => 'Sirop 125 ml',
                'stock' => 19,
                'prix' => 31.00,
                'exp' => $today->copy()->addMonths(10)->format('Y-m-d'),
                'description' => 'Traitement d’appoint des maux de gorge peu intenses sans fièvre.',
                'image_url' => $images['medicine_bottle'],
                'ordonnance' => false,
                'seuil_alerte' => 6,
                'translations' => [
                    'fr' => [
                        'nom' => 'Maxilase',
                        'dci' => 'Alpha-amylase',
                        'dose' => 'Sirop 125 ml',
                        'description' => 'Traitement d’appoint des maux de gorge peu intenses sans fièvre.',
                    ],
                    'en' => [
                        'nom' => 'Maxilase',
                        'dci' => 'Alpha-amylase',
                        'dose' => 'Syrup 125 ml',
                        'description' => 'Adjunct treatment for mild sore throat without fever.',
                    ],
                    'ar' => [
                        'nom' => 'ماكسيلاز',
                        'dci' => 'ألفا أميلاز',
                        'dose' => 'شراب 125 مل',
                        'description' => 'علاج مساعد لآلام الحلق الخفيفة دون حمى.',
                    ],
                ],
            ],
            [
                'nom' => 'Gaviscon',
                'dci' => 'Alginate de sodium + bicarbonate de sodium',
                'molecule' => 'Alginate de sodium + bicarbonate de sodium + carbonate de calcium',
                'code' => 'MED-0015',
                'category' => 'Digestif',
                'dose' => 'Suspension buvable 250 ml',
                'stock' => 34,
                'prix' => 57.00,
                'exp' => $today->copy()->addMonths(11)->format('Y-m-d'),
                'description' => 'Antiacide et alginate indiqué dans le reflux gastro-œsophagien.',
                'image_url' => $images['assorted_pills'],
                'ordonnance' => false,
                'seuil_alerte' => 10,
                'translations' => [
                    'fr' => [
                        'nom' => 'Gaviscon',
                        'dci' => 'Alginate de sodium + bicarbonate de sodium',
                        'dose' => 'Suspension buvable 250 ml',
                        'description' => 'Antiacide et alginate indiqué dans le reflux gastro-œsophagien.',
                    ],
                    'en' => [
                        'nom' => 'Gaviscon',
                        'dci' => 'Sodium alginate + sodium bicarbonate',
                        'dose' => 'Oral suspension 250 ml',
                        'description' => 'Antacid and alginate indicated for gastroesophageal reflux.',
                    ],
                    'ar' => [
                        'nom' => 'جافيسكون',
                        'dci' => 'ألجينات الصوديوم + بيكربونات الصوديوم',
                        'dose' => 'معلق فموي 250 مل',
                        'description' => 'مضاد للحموضة ومركب ألجينات يُستعمل في الارتجاع المعدي المريئي.',
                    ],
                ],
            ],
            [
                'nom' => 'Smecta',
                'dci' => 'Diosmectite',
                'molecule' => 'Diosmectite',
                'code' => 'MED-0016',
                'category' => 'Digestif',
                'dose' => '3 g sachet',
                'stock' => 52,
                'prix' => 29.50,
                'exp' => $today->copy()->addMonths(18)->format('Y-m-d'),
                'description' => 'Adsorbant intestinal utilisé dans le traitement symptomatique de la diarrhée.',
                'image_url' => $images['prescription_bottles'],
                'ordonnance' => false,
                'seuil_alerte' => 12,
                'translations' => [
                    'fr' => [
                        'nom' => 'Smecta',
                        'dci' => 'Diosmectite',
                        'dose' => '3 g sachet',
                        'description' => 'Adsorbant intestinal utilisé dans le traitement symptomatique de la diarrhée.',
                    ],
                    'en' => [
                        'nom' => 'Smecta',
                        'dci' => 'Diosmectite',
                        'dose' => '3 g sachet',
                        'description' => 'Intestinal adsorbent used for symptomatic treatment of diarrhea.',
                    ],
                    'ar' => [
                        'nom' => 'سميكتا',
                        'dci' => 'ديوسمكتيت',
                        'dose' => 'كيس 3 غ',
                        'description' => 'مادة ماصة معوية تُستعمل في العلاج العرضي للإسهال.',
                    ],
                ],
            ],
            [
                'nom' => 'Clarityne',
                'dci' => 'Loratadine',
                'molecule' => 'Loratadine',
                'code' => 'MED-0017',
                'category' => 'Allergies',
                'dose' => '10 mg comprimé',
                'stock' => 29,
                'prix' => 39.00,
                'exp' => $today->copy()->addMonths(9)->format('Y-m-d'),
                'description' => 'Antihistaminique indiqué dans la rhinite allergique et l’urticaire.',
                'image_url' => $images['ibuprofen'],
                'ordonnance' => false,
                'seuil_alerte' => 8,
                'translations' => [
                    'fr' => [
                        'nom' => 'Clarityne',
                        'dci' => 'Loratadine',
                        'dose' => '10 mg comprimé',
                        'description' => 'Antihistaminique indiqué dans la rhinite allergique et l’urticaire.',
                    ],
                    'en' => [
                        'nom' => 'Clarityne',
                        'dci' => 'Loratadine',
                        'dose' => '10 mg tablet',
                        'description' => 'Antihistamine indicated for allergic rhinitis and urticaria.',
                    ],
                    'ar' => [
                        'nom' => 'كلاريتين',
                        'dci' => 'لوراتادين',
                        'dose' => '10 ملغ أقراص',
                        'description' => 'مضاد هيستامين لعلاج التهاب الأنف التحسسي والشرى.',
                    ],
                ],
            ],
            [
                'nom' => 'Aerius',
                'dci' => 'Desloratadine',
                'molecule' => 'Desloratadine',
                'code' => 'MED-0018',
                'category' => 'Allergies',
                'dose' => '5 mg comprimé',
                'stock' => 16,
                'prix' => 68.00,
                'exp' => $today->copy()->addMonths(7)->format('Y-m-d'),
                'description' => 'Antihistaminique de seconde génération pour les symptômes allergiques persistants.',
                'image_url' => $images['b12'],
                'ordonnance' => true,
                'seuil_alerte' => 6,
                'translations' => [
                    'fr' => [
                        'nom' => 'Aerius',
                        'dci' => 'Desloratadine',
                        'dose' => '5 mg comprimé',
                        'description' => 'Antihistaminique de seconde génération pour les symptômes allergiques persistants.',
                    ],
                    'en' => [
                        'nom' => 'Aerius',
                        'dci' => 'Desloratadine',
                        'dose' => '5 mg tablet',
                        'description' => 'Second-generation antihistamine for persistent allergy symptoms.',
                    ],
                    'ar' => [
                        'nom' => 'إيريوس',
                        'dci' => 'ديسلوراتادين',
                        'dose' => '5 ملغ أقراص',
                        'description' => 'مضاد هيستامين من الجيل الثاني لأعراض الحساسية المستمرة.',
                    ],
                ],
            ],
            [
                'nom' => 'Cardensiel',
                'dci' => 'Bisoprolol',
                'molecule' => 'Bisoprolol fumarate',
                'code' => 'MED-0019',
                'category' => 'Cardiologie',
                'dose' => '5 mg comprimé',
                'stock' => 22,
                'prix' => 67.00,
                'exp' => $today->copy()->addMonths(18)->format('Y-m-d'),
                'description' => 'Bêta-bloquant indiqué notamment dans l’hypertension et l’insuffisance cardiaque stable.',
                'image_url' => $images['duodart'],
                'ordonnance' => true,
                'seuil_alerte' => 8,
                'translations' => [
                    'fr' => [
                        'nom' => 'Cardensiel',
                        'dci' => 'Bisoprolol',
                        'dose' => '5 mg comprimé',
                        'description' => 'Bêta-bloquant indiqué notamment dans l’hypertension et l’insuffisance cardiaque stable.',
                    ],
                    'en' => [
                        'nom' => 'Cardensiel',
                        'dci' => 'Bisoprolol',
                        'dose' => '5 mg tablet',
                        'description' => 'Beta blocker indicated for hypertension and stable heart failure.',
                    ],
                    'ar' => [
                        'nom' => 'كاردينسيل',
                        'dci' => 'بيسوبرولول',
                        'dose' => '5 ملغ أقراص',
                        'description' => 'حاصر بيتا يُستعمل خصوصاً لارتفاع الضغط وقصور القلب المستقر.',
                    ],
                ],
            ],
            [
                'nom' => 'Coversyl',
                'dci' => 'Périndopril',
                'molecule' => 'Périndopril arginine',
                'code' => 'MED-0020',
                'category' => 'Cardiologie',
                'dose' => '5 mg comprimé',
                'stock' => 17,
                'prix' => 74.00,
                'exp' => $today->copy()->addMonths(16)->format('Y-m-d'),
                'description' => 'Inhibiteur de l’enzyme de conversion utilisé dans l’hypertension artérielle.',
                'image_url' => $images['amoxicillin_drops'],
                'ordonnance' => true,
                'seuil_alerte' => 6,
                'translations' => [
                    'fr' => [
                        'nom' => 'Coversyl',
                        'dci' => 'Périndopril',
                        'dose' => '5 mg comprimé',
                        'description' => 'Inhibiteur de l’enzyme de conversion utilisé dans l’hypertension artérielle.',
                    ],
                    'en' => [
                        'nom' => 'Coversyl',
                        'dci' => 'Perindopril',
                        'dose' => '5 mg tablet',
                        'description' => 'ACE inhibitor used in hypertension management.',
                    ],
                    'ar' => [
                        'nom' => 'كوفرسيل',
                        'dci' => 'بيريندوبريل',
                        'dose' => '5 ملغ أقراص',
                        'description' => 'مثبط للإنزيم المحول للأنجيوتنسين يُستخدم لعلاج ارتفاع ضغط الدم.',
                    ],
                ],
            ],
            [
                'nom' => 'Glucophage',
                'dci' => 'Metformine',
                'molecule' => 'Metformin hydrochloride',
                'code' => 'MED-0021',
                'category' => 'Diabète',
                'dose' => '850 mg comprimé',
                'stock' => 30,
                'prix' => 45.00,
                'exp' => $today->copy()->addMonths(14)->format('Y-m-d'),
                'description' => 'Antidiabétique oral de première intention dans le diabète de type 2.',
                'image_url' => $images['medicine_bottle'],
                'ordonnance' => true,
                'seuil_alerte' => 10,
                'translations' => [
                    'fr' => [
                        'nom' => 'Glucophage',
                        'dci' => 'Metformine',
                        'dose' => '850 mg comprimé',
                        'description' => 'Antidiabétique oral de première intention dans le diabète de type 2.',
                    ],
                    'en' => [
                        'nom' => 'Glucophage',
                        'dci' => 'Metformin',
                        'dose' => '850 mg tablet',
                        'description' => 'First-line oral antidiabetic medicine for type 2 diabetes.',
                    ],
                    'ar' => [
                        'nom' => 'غلوكوفاج',
                        'dci' => 'ميتفورمين',
                        'dose' => '850 ملغ أقراص',
                        'description' => 'دواء فموي مضاد للسكري يُستخدم كخط أول في السكري من النوع الثاني.',
                    ],
                ],
            ],
            [
                'nom' => 'NovoRapid FlexPen',
                'dci' => 'Insuline asparte',
                'molecule' => 'Insuline asparte',
                'code' => 'MED-0022',
                'category' => 'Diabète',
                'dose' => '100 U/ml stylo prérempli',
                'stock' => 12,
                'prix' => 189.00,
                'exp' => $today->copy()->addMonths(6)->format('Y-m-d'),
                'description' => 'Insuline d’action rapide utilisée pour contrôler la glycémie au moment des repas.',
                'image_url' => $images['prescription_bottles'],
                'ordonnance' => true,
                'seuil_alerte' => 5,
                'translations' => [
                    'fr' => [
                        'nom' => 'NovoRapid FlexPen',
                        'dci' => 'Insuline asparte',
                        'dose' => '100 U/ml stylo prérempli',
                        'description' => 'Insuline d’action rapide utilisée pour contrôler la glycémie au moment des repas.',
                    ],
                    'en' => [
                        'nom' => 'NovoRapid FlexPen',
                        'dci' => 'Insulin aspart',
                        'dose' => '100 U/ml prefilled pen',
                        'description' => 'Rapid-acting insulin used to control blood glucose around mealtime.',
                    ],
                    'ar' => [
                        'nom' => 'نوفورابيد فليكس بن',
                        'dci' => 'أنسولين أسبارت',
                        'dose' => '100 وحدة/مل قلم معبأ مسبقاً',
                        'description' => 'أنسولين سريع المفعول للتحكم في سكر الدم وقت الوجبات.',
                    ],
                ],
            ],
        ];

        foreach ($medicines as $data) {
            $translations = $data['translations'];
            $categoryName = $data['category'];
            unset($data['translations'], $data['category']);

            $data['category_id'] = $categories[$categoryName] ?? null;

            if (!$data['category_id']) {
                continue;
            }

            $medicine = Medicine::updateOrCreate(
                ['code' => $data['code']],
                $data
            );

            foreach ($translations as $locale => $translation) {
                $medicine->translations()->updateOrCreate(
                    ['locale' => $locale],
                    $translation
                );
            }
        }
    }
}
